### ISSUE TITLE
Error on using libraries for compatibility

### ISSUE THREAD

**Issue by kenoss** [kenoss/pyproject-indirect-import-detector#17]
## Environment

```
$ python --version
Python 3.9.1
```

## What I did

Use `pyproject.toml` containing the following line:

```
dataclasses = {version = "^0.8", python = "< 3.7"}
```

## Error

```
$ poetry run pyproject-indirect-import-detector
Traceback (most recent call last):
  File "/home/keno/.cache/pypoetry/virtualenvs/actfw-core-SNNDOo5d-py3.9/bin/pyproject-indirect-import-detector", line 8, in <module>
    sys.exit(_main())
  File "/home/keno/.cache/pypoetry/virtualenvs/actfw-core-SNNDOo5d-py3.9/lib/python3.9/site-packages/pyproject_indirect_import_detector/main.py", line 88, in _main
    _main_aux(args, root)
  File "/home/keno/.cache/pypoetry/virtualenvs/actfw-core-SNNDOo5d-py3.9/lib/python3.9/site-packages/pyproject_indirect_import_detector/main.py", line 51, in _main_aux
    res = _detect(pyproject, False)
  File "/home/keno/.cache/pypoetry/virtualenvs/actfw-core-SNNDOo5d-py3.9/lib/python3.9/site-packages/pyproject_indirect_import_detector/main.py", line 26, in _detect
    module_to_proj_ = pyproject.load_module_to_proj(dev)
  File "/home/keno/.cache/pypoetry/virtualenvs/actfw-core-SNNDOo5d-py3.9/lib/python3.9/site-packages/pyproject_indirect_import_detector/pyproject.py", line 112, in load_module_to_proj
    proj_to_modules_ = _load_proj_to_modules(
  File "/home/keno/.cache/pypoetry/virtualenvs/actfw-core-SNNDOo5d-py3.9/lib/python3.9/site-packages/pyproject_indirect_import_detector/domain.py", line 63, in _load_proj_to_modules
    proj_to_modules_dep = dict((proj, _get_modules(proj)) for proj in project_names)
  File "/home/keno/.cache/pypoetry/virtualenvs/actfw-core-SNNDOo5d-py3.9/lib/python3.9/site-packages/pyproject_indirect_import_detector/domain.py", line 63, in <genexpr>
    proj_to_modules_dep = dict((proj, _get_modules(proj)) for proj in project_names)
  File "/home/keno/.cache/pypoetry/virtualenvs/actfw-core-SNNDOo5d-py3.9/lib/python3.9/site-packages/pyproject_indirect_import_detector/domain.py", line 20, in _get_modules
    dist = Distribution.from_name(project_name)
  File "/home/keno/.pyenv/versions/3.9.1/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: dataclasses
```

**Comment by kenoss** [comment]
## Possible solutions

A. Provide a configuration `alternative_project_to_modules_map`.

That changes the behavior as the following:

- Do not search a distribution from the environment.
- Use the designated `proj_to_modules` for the package.

B. Provide a configuration `prevent_search_packages`.

That changes:

- Do not search a distribution from the environment.

In the reported case, `dataclasses` is in stdlib of `python >= 3.9` and I guess the run will pass.

---

I feel B is too ad-hoc and I prefer A.

**Comment by kenoss** [comment]
C. Provide configuration `exclude_projects`.

This configuration is orthogonal to `exclude_modules` and users use these configurations together.

I've done it.
